pythonindia/inpycon2025

netlify.toml, src/_data/env.js
Previous PR fixed server deployment but local deployment was failing.
This PR fixes local deployment.
=> fix: use / for dev environment

src/_includes/navbar.njk, src/_includes/section.header.njk, src/cfp.md
CFP webpage added
CFP Submit button added on Homepage
CFP Content page added on Nav bar
=> Adding CFP Webpage 

src/_includes/components/cube.njk, src/_includes/landing/keynotes.njk
- Created a cube component
- Made changes in the keynote section and added some animations to the same
=> Keynote Speaker Section

src/_includes/components/button.njk, src/venue.njk, tailwind.config.js
- Rotate the button to 40 degrees
- Fixing arrow image in venue page
=> fix: Fixes issues with image and button rotate

src/index.njk
=> removed keynotes section till keynotes announced

src/_includes/landing/sponsors.njk
=> fixed issue #63

src/coc/guidelines.njk
Correcting CoC reporting link as per issue #74
=> correcting CoC reporting link

src/_includes/components/button.njk, src/_includes/landing/sponsors.njk
=> add get in touch button for sponsors

src/coc/guidelines.njk
Fixes Issue: https://github.com/pythonindia/inpycon2025/issues/82
Updated: The Transparency Report link on coc page.
=> Link updated:  In The Transparency Report link on coc page.

src/_includes/js.njk
=> fix: highlight navbar for hierarchical items

src/_includes/components/button.njk, src/cfp.njk
Button disabled and note added for proposals submission
Fixes issue: https://github.com/pythonindia/inpycon2025/issues/80
=> CFP page update - Proposals closed

src/_includes/landing/sponsors.njk
=> fix: add some spacing between the Sponsor section buttons

src/_includes/components/flat-card.njk
=> Removed hover animation on card

src/venue.njk
=> chore: change 2024 to 2025

src/_includes/landing/hero-banner.njk
=> Fixed hero image alignment

src/_includes/js.njk, src/_includes/landing/hero-banner.njk, src/_includes/navbar.njk, src/index.njk
Fixes #78 
This is how it currently looks now, as per design:
But I feel we should have logo and get tickets button as well in the navbar (which is not in the design), Will look something like :
=> Added Navbar in Hero section

src/_includes/footer.njk, src/_includes/landing/communities.njk, src/_includes/landing/sponsors.njk
Changed the blue background shades
from 
bg-blue-600 (#2563EB)
to
bg-pycon-blue (#4E62F5)
Fixed issue : #108
=> Fix: unify blue background shades in all sections

Makefile, netlify.toml, package.json
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
=> fetch schedule from pretalx on build

Makefile, src/_data/roomColors.json, src/program/schedule.njk
- Workshop Schedule
- Made the cards cover up the entire rows
- For small devices order by event start time
- Resolves #150
=> Workshop Schedule

src/_includes/landing/sponsors.njk
- Fixed url for sponsors section
- Made alignment changes
=> Sponsors Section URL and Alignment Fix

src/_includes/landing/hero.njk
=> update to hero section buttons

src/cfp/index.njk, src/cfp/panel.njk, src/cfp/poster.njk, src/cfp/talks.njk
- Extended Poster Presentations
- Update status of all other pages to reflect current state.
=> Update CFP related pages

src/_data/menuItems.json, src/venue/about-bengaluru.njk
About Bengaluru page #171 
Few things:
- Is it possible to have any icon from the hero section which is actually relevant to Bengaluru?
- What should be the url for this page?
- I've used the content from the previous year page, is it still relevant or do we need to update it?
URL: https://deploy-preview-185--inpycon2025.netlify.app/venue/about-bengaluru/
cc: @anistark @farhaanbukhsh @palnabarun @bhavin192
=> About Bengaluru

src/_data/menuItems.json, src/_includes/navbar.njk, src/attend/tickets.njk, src/program/speakers.njk
This solves issue #197 
- Alignment fixes on small and medium devices
- Link speakers image to cfp page speaker details
This covers PR #122 as well
=> Improvements to speakers section and navbar

src/program/schedule.njk, src/static/js/schedule.js
Added Dev Sprint to Schedule and linked it to Dev sPRINT PAGE
=> chore: add dev sprint to schedule

.eleventy.js, src/_data/roomColors.json, src/program/schedule.njk
This is how the schedule would be displayed with open spaces
=> chore: improvements to schedule to display open spaces

src/_data/team.json
Added my volunteer details to the source
=> updated Arthi volunteer details
